[package]
name = "miniquad-js-interop-demo"
version = "0.1.0"
authors = ["not-fl3 <not.fl3@gmail.com>"]
edition = "2018"

[dependencies]
miniquad = { version = "0.2", features = ["log-impl"] }
sapp-jsutils = "0.1"
